const NOTIFICATION_TYPE = {
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
    INFO: 'INFO',
    WARNING: 'WARNING'
}

const LOCAL_STORAGE_KEY_TYPE = {
    THEME_MODE: 'THEME_MODE',
}


export {
    NOTIFICATION_TYPE,
    LOCAL_STORAGE_KEY_TYPE
}